server:
  port: 8080

spring:
  application:
    name: todo

    # DB 설정(local)
  #  datasource:
  #    driver-class-name: org.mariadb.jdbc.Driver
  #    url: jdbc:mariadb://localhost:3306/todolist?characterEncoding=UTF-8&serverTimezone=UTC
  #    username: root
  #    password: 3301
  #    hikari:
  #      connection-test-query: SELECT NOW() FROM DUAL

  # DB 설정 (cloud)
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://database:6033/todolist?characterEncoding=UTF-8&serverTimezone=UTC
    username: todo_user
    password: todo_password
    hikari:
      connection-test-query: SELECT NOW() FROM DUAL

  sql:
    init:
      mode: always
      encoding: utf-8
      platform: mariadb
  #      data-locations: classpath:database/2-data.sql

  # JPA 설정
  jpa:
    hibernate:
      # 배포 시 변경 (create -> none)
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        highlight_sql: true
      #SQL 로깅 설정(더미 데이터)
#    defer-datasource-initialization: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace

