version: "3"

services:
  ### spring boot
  app:
    container_name: todo-container
    build: .
    # 의존 관계 설정
    depends_on:
      - database
    # 포트 포워딩
    ports:
      - "8888:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://database:3306/todolist?characterEncoding=UTF-8&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: todo_user
      SPRING_DATASOURCE_PASSWORD: todo_password
    links:
      - database
    restart: always
    platform: linux/amd64

    ### maria db
  database:
    image: mariadb:11.3.2
    container_name: todo-db-container
    environment:
      MARIADB_ROOT_PASSWORD: 3301
      MARIADB_USER: todo_user
      MARIADB_PASSWORD: todo_password
      MARIADB_DATABASE: todolist
    ports:
      - "6033:3306"
    volumes:
      - ./src/main/resources/database/1-schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./src/main/resources/database/2-data.sql:/docker-entrypoint-initdb.d/2-data.sql